
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 9999

spring:
  cloud:
    gateway:
      routes:
        - id: microservice1
          uri: lb://microservice1 #uri: http://localhost:8081/
          predicates:
            - Path=/ms1/**
        - id: microservice2
          uri: lb://microservice2 #uri: http://localhost:8082/
          predicates:
            - Path=/ms2/**
  application:
    name: gateway